# Generated by Django 4.1.4 on 2022-12-27 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostImage', models.ImageField(null=True, upload_to='postimage/')),
                ('PostTitle', models.CharField(max_length=70)),
                ('PostDescrption', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='SingelPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.postmodel')),
            ],
        ),
    ]
