# Generated by Django 4.1.3 on 2022-12-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='LongPostDescrption',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='PostDescrption',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='PostTitle',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.DeleteModel(
            name='SingelPostModel',
        ),
    ]
