# Generated by Django 4.1.3 on 2022-12-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_postmodel_longpostdescrption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='LongPostDescrption',
            field=models.TextField(null=True),
        ),
    ]
