# Generated by Django 4.1.4 on 2022-12-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarsImage', models.ImageField(upload_to='media/cars')),
                ('CarsName', models.CharField(max_length=100)),
                ('CarsModel', models.CharField(max_length=250)),
                ('CarsSalary', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SingleCarmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarsMileage', models.IntegerField()),
                ('CarsTransmision', models.IntegerField(choices=[(1, 'Automatic'), (2, 'Manual')], default=2)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.carsmodel')),
            ],
        ),
    ]
