# Generated by Django 4.1.4 on 2022-12-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_singlecarmodel_cars_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsmodel',
            name='CarsSalary',
            field=models.IntegerField(),
        ),
    ]
