# Generated by Django 4.1.4 on 2022-12-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_carsmodel_carsimage_delete_singlecarmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsmodel',
            name='CarsImage',
        ),
    ]
