# Generated by Django 4.1.4 on 2022-12-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_carsmodel_carsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsmodel',
            name='CarsImage',
            field=models.ImageField(null=True, upload_to='media/cars'),
        ),
    ]
