# Generated by Django 4.1.4 on 2022-12-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_singlecarmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsmodel',
            name='CarsImage',
            field=models.ImageField(null=True, upload_to='cars/'),
        ),
    ]
