# Generated by Django 4.1.4 on 2022-12-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_singlecarmodel_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlecarmodel',
            name='CarsSerial',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
