# Generated by Django 4.1.4 on 2022-12-29 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_remove_singlecarmodel_car_singlecarmodel_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlecarmodel',
            name='car',
        ),
        migrations.AddField(
            model_name='singlecarmodel',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.carsmodel'),
        ),
    ]
