# Generated by Django 4.1.4 on 2022-12-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_carsmodel_carsluggage_carsmodel_carsmileage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarsModel',
        ),
    ]
