# Generated by Django 4.1.4 on 2022-12-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0017_delete_carsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceImage', models.ImageField(null=True, upload_to='Serviceimage/')),
                ('ServiceTitle', models.CharField(max_length=70, null=True)),
                ('ServiceDescrption', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
