# Generated by Django 4.1.4 on 2022-12-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarsImage', models.ImageField(null=True, upload_to='cars/')),
                ('CarsName', models.CharField(max_length=100)),
                ('CarsModel', models.CharField(max_length=250)),
                ('CarsSalary', models.IntegerField(null=True)),
                ('CarsMileage', models.IntegerField(null=True)),
                ('CarsSerial', models.CharField(max_length=100, null=True)),
                ('CarsTransmision', models.IntegerField(choices=[(1, 'Automatic'), (2, 'Manual')], default=2)),
                ('Cars_Seats', models.IntegerField(choices=[(1, '2'), (2, '4'), (3, '5')], default=2)),
                ('CarsLuggage', models.IntegerField(choices=[(1, '2'), (2, '3'), (3, '4'), (4, '5')], default=2)),
                ('Cars_Fuel', models.IntegerField(choices=[(1, 'gas'), (2, 'Petrol'), (3, 'electric'), (4, 'hybrid(Patrol & gas)'), (5, 'hybrid(Patrol & electric)')], default=3)),
            ],
        ),
    ]
